apiVersion: apps/v1
kind: Deployment
metadata:
  name: proompteng-proompteng-operator
  namespace: proompteng-system
  labels:
    app.kubernetes.io/name: proompteng-operator
    app.kubernetes.io/instance: proompteng
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: proompteng
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: proompteng-operator
      app.kubernetes.io/instance: proompteng
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: proompteng-operator
        app.kubernetes.io/instance: proompteng
        app.kubernetes.io/version: "0.1.0"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: operator
        app.kubernetes.io/part-of: proompteng
    spec:
      serviceAccountName: proompteng-proompteng-operator
      automountServiceAccountToken: true
      containers:
        - name: operator
          image: ghcr.io/proompteng/operator:0.1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: CONFIG_PATH
              value: /config/config.yaml
            - name: LOG_LEVEL
              value: "info"
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
            - name: healthz
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: proompteng-proompteng-operator-config
