{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "proompteng-operator.fullname" . }}
  labels:
    {{- include "proompteng-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - events
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - proompteng.ai
    resources:
      - agents
      - agents/status
      - memories
      - memories/status
      - tools
      - connectors
      - policies
      - modelroutes
      - modelroutes/status
      - agentservices
      - agentservices/status
      - evalsuites
      - evalsuites/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "proompteng-operator.fullname" . }}
  labels:
    {{- include "proompteng-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "proompteng-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "proompteng-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
