apiVersion: v1
kind: Service
metadata:
  name: {{ include "proompteng-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "proompteng-operator.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  selector:
    {{- include "proompteng-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      protocol: TCP
      targetPort: metrics
    - name: healthz
      port: 8081
      protocol: TCP
      targetPort: healthz
