apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agentservices.proompteng.ai
spec:
  group: proompteng.ai
  scope: Namespaced
  names:
    plural: agentservices
    singular: agentservice
    kind: AgentService
    shortNames:
      - agsvc
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Auth
          type: string
          jsonPath: .spec.auth.type
        - name: Agent
          type: string
          jsonPath: .spec.agentRef.name
      schema:
        openAPIV3Schema:
          type: object
          description: Exposes an agent behind a service facade with auth and rate limiting.
          properties:
            spec:
              type: object
              required:
                - agentRef
              properties:
                agentRef:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                auth:
                  type: object
                  properties:
                    type:
                      type: string
                      enum:
                        - none
                        - apiKey
                        - oidc
                    apiKeySecretRef:
                      type: string
                    oidcIssuer:
                      type: string
                rateLimit:
                  type: object
                  properties:
                    requestsPerMinute:
                      type: integer
                      format: int32
                    burst:
                      type: integer
                      format: int32
                transport:
                  type: object
                  properties:
                    protocol:
                      type: string
                    publicEndpoint:
                      type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                observedGeneration:
                  type: integer
                  format: int64
                lastTransitionTime:
                  type: string
                  format: date-time
          required:
            - spec
